# prometheus config file

global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'

scrape_configs:
  #self (prometheus)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # python app
  - job_name: 'docker stats'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['172.17.0.1:8080']
