# prometheus config file

global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'

scrape_configs:

  # system_monitoring
  - job_name: 'System Monitoring Python'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['172.17.0.1:9999']
     
