# docker-compose file
# runs a docker container from the promstats image
# pushes docker stats to port 8080

version: '3'
services:
  myapp:
    image: promstats
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    network_mode: bridge
